import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { api } from "../api";
import type { ShipmentDetail as Detail } from "../types";
import {
  BandPill, Card, DriverBars, Empty, ErrorState, LiveBadge, RiskScore, Skeleton,
} from "../components/ui";
import { hoursBetween, num, pct, usd, when } from "../lib/format";

const VALIDATION_COPY: Record<string, string> = {
  real_weather_simulated_flights:
    "Trained on real recorded weather. Flight records are simulated.",
  simulated: "Trained on simulated data pending client history.",
};

export default function ShipmentDetail() {
  const { id = "" } = useParams();
  const [s, setS] = useState<Detail | null>(null);
  const [error, setError] = useState("");

  const load = useCallback(() => {
    setError("");
    api.shipment(id).then(setS).catch((e) => setError(e.message));
  }, [id]);

  useEffect(load, [load]);

  if (error) return <ErrorState error={error} onRetry={load} />;
  if (!s) return <Skeleton rows={10} />;

  const risk = s.risk;
  const band = risk?.band ?? "LOW";
  const slip = hoursBetween(s.predicted_delivery, s.promised_delivery);
  const signals = s.signals ?? {};
  const signalKeys = Object.keys(signals);

  return (
    <div className="space-y-5">
      <Link to="/" className="text-sm text-text-muted hover:text-ups-brown-800 flex items-center gap-1">
        <ArrowLeft size={14} /> Back to risk queue
      </Link>

      {/* Header */}
      <Card>
        <div className="flex flex-wrap items-start gap-8">
          <div>
            <div className="flex items-center gap-3">
              <h2 className="text-2xl font-bold text-ups-brown-800">{s.id}</h2>
              <BandPill band={band} />
            </div>
            <p className="text-sm text-text-muted mt-1">
              {s.mode} &middot; {s.carrier} &middot; {s.service_level}
            </p>
            <p className="text-sm mt-2 font-medium">
              {s.origin.name} ({s.origin.code}) &rarr; {s.destination.name} ({s.destination.code})
            </p>
            {risk && (
              <p className="text-[11px] text-text-muted mt-2 max-w-md"
                 title={VALIDATION_COPY[risk.validation_status] ?? risk.validation_status}>
                Model: <strong>{risk.model_used}</strong> &middot;{" "}
                {VALIDATION_COPY[risk.validation_status] ?? risk.validation_status}
              </p>
            )}
          </div>

          <div className="flex items-center gap-10 ml-auto">
            <div>
              <RiskScore score={risk?.score ?? 0} band={band} size="lg" />
              <p className="text-xs text-text-muted">risk score out of 10</p>
            </div>
            <Figure value={pct(risk?.breach_probability ?? 0)}
              caption={"chance of missing the promised date"} />
            <Figure value={num(risk?.predicted_delay_hours ?? 0) + "h"}
              caption="expected lateness if it slips" />
            <Figure value={pct(risk?.confidence ?? 0)}
              caption="how sure the model is here" />
          </div>
        </div>
      </Card>

      <div className="grid lg:grid-cols-2 gap-5">
        {/* Why this score */}
        <Card title="Why this score"
              subtitle="The three factors pushing this score the most">
          <DriverBars drivers={s.drivers} />
        </Card>

        {/* Recommendation */}
        <div className="space-y-5">
          {s.recommendation ? (
            <div className="bg-ups-gold-soft border border-border-warm border-l-4 border-l-ups-gold rounded-lg p-5">
              <div className="flex items-center gap-2 flex-wrap">
                <span className="font-bold text-ups-brown-900 tracking-wide">
                  {s.recommendation.action.replace(/_/g, " ")}
                </span>
                <span className="text-[10px] font-bold uppercase bg-ups-brown-800 text-white px-1.5 py-0.5 rounded">
                  {s.recommendation.urgency}
                </span>
              </div>
              <p className="font-semibold mt-2 text-ups-brown-800">{s.recommendation.headline}</p>
              <p className="text-sm text-text-main mt-1.5 leading-relaxed">{s.recommendation.detail}</p>
              <p className="text-[11px] text-text-muted mt-3">
                generated by: {s.recommendation.generated_by}
              </p>
            </div>
          ) : (
            <Card title="Recommended action"><Empty>No recommendation available.</Empty></Card>
          )}

          <Card title="Delivery timeline">
            <div className="grid grid-cols-3 gap-3 text-sm">
              <Field label="Departed" value={when(s.departed_at)} />
              <Field label="Promised" value={when(s.promised_delivery)} />
              <Field label="Predicted" value={when(s.predicted_delivery)}
                     danger={slip > 0} />
            </div>
            {slip > 0 && (
              <p className="mt-3 text-sm font-semibold text-risk-high">
                Predicted slip: {num(slip)} hours past the promise
              </p>
            )}
            <div className="mt-4">
              <div className="h-2 bg-surface-alt rounded overflow-hidden">
                <div className="h-full bg-ups-brown-600" style={{ width: s.progress_pct + "%" }} />
              </div>
              <p className="text-xs text-text-muted mt-1">
                {Math.round(s.progress_pct)}% of the journey complete &middot;{" "}
                {usd(s.value_usd)} of goods &middot; {s.weight_kg} kg
              </p>
            </div>
          </Card>
        </div>
      </div>

      {/* Live signals */}
      <Card title="Live risk signals"
            subtitle="External data feeding this score, each labelled live or simulated">
        {signalKeys.length === 0 ? (
          <Empty>No live signal data yet. Run &ldquo;Refresh live signals&rdquo; on the risk queue.</Empty>
        ) : (
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {signalKeys.map((k) => {
              const sig = signals[k] ?? {};
              return (
                <div key={k} className="border border-border-warm rounded-lg p-3">
                  <div className="flex items-center justify-between gap-2">
                    <span className="font-semibold text-sm capitalize text-ups-brown-800">
                      {k.replace(/_/g, " ")}
                    </span>
                    <LiveBadge live={sig.is_live} source={sig.source} />
                  </div>
                  <div className="text-2xl font-bold tabular-nums mt-1 text-ups-brown-800">
                    {sig.severity != null ? num(sig.severity, 2) : "--"}
                  </div>
                  <p className="text-xs text-text-muted">severity, 0 to 1</p>
                  {sig.detail && <p className="text-xs mt-1.5">{sig.detail}</p>}
                </div>
              );
            })}
          </div>
        )}
      </Card>
    </div>
  );
}

function Figure({ value, caption }: { value: string; caption: string }) {
  return (
    <div className="max-w-[7.5rem]">
      <div className="text-2xl font-bold tabular-nums text-ups-brown-800">{value}</div>
      <p className="text-xs text-text-muted leading-snug mt-0.5">{caption}</p>
    </div>
  );
}

function Field({ label, value, danger }: { label: string; value: string; danger?: boolean }) {
  return (
    <div>
      <div className="text-xs uppercase tracking-wide text-text-muted font-semibold">{label}</div>
      <div className={"font-medium mt-0.5 " + (danger ? "text-risk-high" : "")}>{value}</div>
    </div>
  );
}
